apiVersion: argoproj.io/v1aplha1
kind: Application
metadata:
  name: homeserver-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maxfelius/homeArgoCDApplication.git
    targetRevision: HEAD
    path: applications
  destnation:
    server: https://kubernetes.default.svc
    namespace: homeserver

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
